# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soapbox', '0002_is_global_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_regex',
            field=models.BooleanField(
                default=False,
                help_text='If checked, the URL field will be treated as a '
                          'regular expression while matching.'
            ),
        ),
    ]
